"""baseline

Revision ID: 369cb5d4c292
Revises: 
Create Date: 2026-09-07 13:02:11.245108

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '369cb5d4c292'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
