"""add facial_assessments column and report_feature_visuals table

Revision ID: c1c275b66efa
Revises: 115f55ea57f6
Create Date: 2026-09-11 17:17:10.953408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c275b66efa'
down_revision: Union[str, Sequence[str], None] = '115f55ea57f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_feature_visuals',
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_reason', sa.String(length=32), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'feature')
    )
    op.add_column('facial_analysis_results', sa.Column('facial_assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facial_analysis_results', 'facial_assessments')
    op.drop_table('report_feature_visuals')
    # ### end Alembic commands ###
