"""add ai_visuals table

Revision ID: c2ed688145e5
Revises: c1c275b66efa
Create Date: 2026-09-13 22:58:46.668705

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2ed688145e5'
down_revision: str | Sequence[str] | None = 'c1c275b66efa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_visuals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('variation_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.String(length=600), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_reason', sa.String(length=32), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'variation_index')
    )
    op.create_index(op.f('ix_ai_visuals_user_id'), 'ai_visuals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_visuals_user_id'), table_name='ai_visuals')
    op.drop_table('ai_visuals')
    # ### end Alembic commands ###
