"""add updated_at to facial_analysis_results

Revision ID: cc5f9ab0e1e0
Revises: cb9dcbc3b69d
Create Date: 2026-09-22 11:33:37.655679

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc5f9ab0e1e0'
down_revision: str | Sequence[str] | None = 'cb9dcbc3b69d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_analysis_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facial_analysis_results', 'updated_at')
    # ### end Alembic commands ###
