"""add reports and report_pdf_blobs tables

Revision ID: d3e9eb285ce3
Revises: 1c626dc935d6
Create Date: 2026-09-08 17:28:39.883848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e9eb285ce3'
down_revision: Union[str, Sequence[str], None] = '1c626dc935d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_pdf_blobs',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_response_id', sa.UUID(), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_reference', sa.String(length=300), nullable=True),
    sa.Column('publish_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['facial_analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_response_id'], ['questionnaire_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_result_id'), 'reports', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_reports_questionnaire_response_id'), 'reports', ['questionnaire_response_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_questionnaire_response_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_result_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('report_pdf_blobs')
    # ### end Alembic commands ###
